name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      APP_ID: ${{ secrets.FIREBASE_APP_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create firebase-config.js
        run: |
          echo "window.firebaseConfig = {
            apiKey: '${API_KEY}',
            authDomain: '${AUTH_DOMAIN}',
            projectId: '${PROJECT_ID}',
            storageBucket: '${STORAGE_BUCKET}',
            messagingSenderId: '${MESSAGING_SENDER_ID}',
            appId: '${APP_ID}'
          };" > public/firebase-config.js

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

